---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: ovn-central:ovn-controller
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ ansible_os_family }}.yml"
  tasks:
    - name: get Wand GPI files
      get_url:
        url: https://packages.wand.net.nz/keyring.gpg
        dest: /etc/apt/trusted.gpg.d/wand.gpg
      become: yes
    - name: add WAND Debian Repo
      apt_repository:
        repo: "deb https://packages.wand.net.nz {{ ansible_lsb.codename }} main"
        state: present
      become: yes
    - name: install OpenVSwitch packages
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ openvswitch_pkgs }}"
    - name: install Open Virtual Network components
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ ovn_pkgs }}"
    - name: start OpenVSwitch services
      service:
        name: "{{ openvswitch_service }}"
        state: started
- hosts: ovn-central
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ ansible_os_family }}.yml"
  tasks:
    - name: install Open Virtual Network central components
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ ovn_central_pkgs }}"
    - name: enable remote connections to southbound and northbound dbs
      lineinfile:
        path: /etc/default/ovn-central
        line: "OVN_CTL_OPTS=\" --db-sb-create-insecure-remote=yes --db-nb-create-insecure-remote=yes\""
        state: present
      become: yes
      when: ansible_os_family == "Debian"
    - name: start OVN northbound database services
      service:
        name: "{{ ovn_central_service }}"
        state: restarted
      become: yes

- hosts: ovn-controller
  vars:
    ovn_central_ips: "{{ groups['ovn-central'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }}"
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: "{{ item }}"
      with_items:
        - "{{ ansible_os_family }}.yml"
  tasks:
    - name: stop the ovn-controller service
      service:
        name: "{{ ovn_controller_service }}"
        state: stopped
      ignore_errors: True
    - name: configure OpenVSwitch databases
      command: "ovs-vsctl set open . external-ids:ovn-remote=tcp:{{ item }}:6642"
      with_items: "{{ ovn_central_ips }}"
      become: yes
    - name: enable overlay network protocols
      command: "ovs-vsctl set open . external-ids:ovn-encap-type=geneve,vxlan"
      become: yes
    - name: configure the overlay network local endpoint IP address.
      command: "ovs-vsctl set open . external-ids:ovn-encap-ip={{ ansible_default_ipv4.address }}"
      become: yes
    - name: start the ovn-controller service
      service:
        name: "{{ ovn_controller_service }}"
        state: started
      ignore_errors: True
